insert into Users (login, password, email, role, phone, name, surname) values ('ikaradzas0', 'GRunDorA83', 'ikaradzas0@1und1.de', 'admin', '686 713 1848', 'Iris', 'Karadzas');
insert into Users (login, password, email, role, phone, name, surname) values ('lchurchill1', 'nw8GPC3', 'lchurchill1@engadget.com', 'user', '655 127 0122', 'Linc', 'Churchill');
insert into Users (login, password, email, role, phone, name, surname) values ('esoigoux2', 'lFPgKx', 'esoigoux2@woothemes.com', 'admin', '823 440 3596', 'Eugene', 'Soigoux');
insert into Users (login, password, email, role, phone, name, surname) values ('sfranzman3', 'ZumvrFpRlw', 'sfranzman3@canalblog.com', 'admin', '262 425 1748', 'Sarena', 'Franzman');
insert into Users (login, password, email, role, phone, name, surname) values ('fbearne4', 'rYd4lhwOhL', 'fbearne4@bluehost.com', 'user', '430 619 9342', 'Fanchon', 'Bearne');
insert into Users (login, password, email, role, phone, name, surname) values ('cpentercost5', 'nPtvPhF', 'cpentercost5@marketwatch.com', 'admin', '225 645 4939', 'Cyrille', 'Pentercost');
insert into Users (login, password, email, role, phone, name, surname) values ('decob6', 'r26ufyyFmbJ', 'decob6@wp.com', 'user', '695 204 1699', 'Dominic', 'Ecob');
insert into Users (login, password, email, role, phone, name, surname) values ('mdukes7', 'utuFlJDNZ5vQ', 'mdukes7@so-net.ne.jp', 'user', '726 149 9816', 'Mort', 'Dukes');
insert into Users (login, password, email, role, phone, name, surname) values ('evanbrug8', '3kjMoC8H62', 'evanbrug8@joomla.org', 'user', '856 416 6243', 'Emlyn', 'Van Brug');
insert into Users (login, password, email, role, phone, name, surname) values ('mchampe9', 'mdoVAD4Ct', 'mchampe9@networkadvertising.org', 'user', '696 983 4745', 'Marcia', 'Champe');
insert into Users (login, password, email, role, phone, name, surname) values ('cklinka', 'iPD7xkIg9', 'cklinka@boston.com', 'admin', '307 548 2573', 'Chico', 'Klink');
insert into Users (login, password, email, role, phone, name, surname) values ('mbremleyb', 'QjTiF4', 'mbremleyb@marketwatch.com', 'user', null, 'Melany', 'Bremley');
insert into Users (login, password, email, role, phone, name, surname) values ('ntussainec', 'rniCvj7LU', 'ntussainec@sun.com', 'admin', null, 'Nicola', 'Tussaine');
insert into Users (login, password, email, role, phone, name, surname) values ('wkortingd', 'JMb1Tg2LtB', 'wkortingd@goo.ne.jp', 'user', '763 359 8706', 'Whitby', 'Korting');
insert into Users (login, password, email, role, phone, name, surname) values ('tpenhaluricke', 'sAqRfYU7', 'tpenhaluricke@wikia.com', 'user', '927 677 1833', 'Tallou', 'Penhalurick');
insert into Users (login, password, email, role, phone, name, surname) values ('nhabronf', 'as0bce', 'nhabronf@networksolutions.com', 'admin', null, 'Nolan', 'Habron');
insert into Users (login, password, email, role, phone, name, surname) values ('iloughnang', 'ZXVywbDAY', 'iloughnang@yellowbook.com', 'admin', '207 298 3228', 'Idelle', 'Loughnan');
insert into Users (login, password, email, role, phone, name, surname) values ('tyellowleesh', 'Un8N8tk6XU', 'tyellowleesh@meetup.com', 'admin', '127 199 3259', 'Tarra', 'Yellowlees');
insert into Users (login, password, email, role, phone, name, surname) values ('fbargei', 'niyw8nD', 'fbargei@wordpress.com', 'user', '550 132 8604', 'Florencia', 'Barge');
insert into Users (login, password, email, role, phone, name, surname) values ('lbedinnj', 'z0FBao7fN', 'lbedinnj@statcounter.com', 'admin', null, 'Lorens', 'Bedinn');
insert into Users (login, password, email, role, phone, name, surname) values ('abrackk', 'ejoBv4L3f', 'abrackk@tumblr.com', 'admin', '690 169 4928', 'Audre', 'Brack');
insert into Users (login, password, email, role, phone, name, surname) values ('kcastrol', 'GPQWUQu', 'kcastrol@google.ca', 'admin', '819 370 2284', 'Kim', 'Castro');
insert into Users (login, password, email, role, phone, name, surname) values ('emateusm', 'G0bbjG1iRMLd', 'emateusm@blog.com', 'user', null, 'Eryn', 'Mateus');
insert into Users (login, password, email, role, phone, name, surname) values ('jleteurtren', 'GALmBev0nlF', 'jleteurtren@phpbb.com', 'user', '181 773 1753', 'Joni', 'Leteurtre');
insert into Users (login, password, email, role, phone, name, surname) values ('ckirwano', 'joZNyq3QG', 'ckirwano@sakura.ne.jp', 'admin', null, 'Cyrillus', 'Kirwan');
insert into Users (login, password, email, role, phone, name, surname) values ('dseversp', 'Fqpq7n', 'dseversp@wordpress.org', 'user', '405 594 6864', 'Desmund', 'Severs');
insert into Users (login, password, email, role, phone, name, surname) values ('wcambleq', 'fIBsbUbCqAA', 'wcambleq@usnews.com', 'user', '156 317 1833', 'Willa', 'Camble');
insert into Users (login, password, email, role, phone, name, surname) values ('gbourchierr', 'w3y3pZpT', 'gbourchierr@cisco.com', 'admin', null, 'Garrot', 'Bourchier');
insert into Users (login, password, email, role, phone, name, surname) values ('mpaulsens', 'FMzv68cr', 'mpaulsens@auda.org.au', 'admin', '749 474 6022', 'Maddi', 'Paulsen');
insert into Users (login, password, email, role, phone, name, surname) values ('npoynsert', '7NhOIjwRbgE3', 'npoynsert@youku.com', 'user', '176 860 0399', 'Nathanial', 'Poynser');
insert into Users (login, password, email, role, phone, name, surname) values ('bdottrellu', '3Dh54TQQQR', 'bdottrellu@delicious.com', 'user', null, 'Basile', 'Dottrell');
insert into Users (login, password, email, role, phone, name, surname) values ('elongleyv', 'Z7iOYTqYwdhl', 'elongleyv@nasa.gov', 'user', '575 947 2231', 'Egbert', 'Longley');
insert into Users (login, password, email, role, phone, name, surname) values ('stashw', 'B0ozfm', 'stashw@slate.com', 'user', null, 'Sherwood', 'Tash');
insert into Users (login, password, email, role, phone, name, surname) values ('pginnetyx', 'goiepn92', 'pginnetyx@google.pl', 'user', null, 'Paul', 'Ginnety');
insert into Users (login, password, email, role, phone, name, surname) values ('nmapisy', 'AHIhwE3xqu67', 'nmapisy@si.edu', 'user', '507 371 9626', 'Nils', 'Mapis');
insert into Users (login, password, email, role, phone, name, surname) values ('tiozefovichz', 'vrsd9h1', 'tiozefovichz@sohu.com', 'user', null, 'Taryn', 'Iozefovich');
insert into Users (login, password, email, role, phone, name, surname) values ('jjermey10', 'oiuxhbhrac', 'jjermey10@twitpic.com', 'admin', '262 826 5755', 'Joey', 'Jermey');
insert into Users (login, password, email, role, phone, name, surname) values ('mlatch11', 'Z7AT9KO', 'mlatch11@europa.eu', 'user', '914 172 8925', 'Moselle', 'Latch');
insert into Users (login, password, email, role, phone, name, surname) values ('tklemensiewicz12', 'PoC9zJnh', 'tklemensiewicz12@domainmarket.com', 'admin', '686 609 2148', 'Trude', 'Klemensiewicz');
insert into Users (login, password, email, role, phone, name, surname) values ('sbussen13', '0g8Eag3u9uli', 'sbussen13@cpanel.net', 'user', null, 'Sarita', 'Bussen');
insert into Users (login, password, email, role, phone, name, surname) values ('cdealey14', 'grEUG1QBmiu', 'cdealey14@army.mil', 'user', '205 398 0851', 'Cory', 'Dealey');
insert into Users (login, password, email, role, phone, name, surname) values ('jcaitlin15', 'gT1HQZ4RLRq9', 'jcaitlin15@walmart.com', 'admin', '969 207 0133', 'Jimmy', 'Caitlin');
insert into Users (login, password, email, role, phone, name, surname) values ('jtrevena16', 'Yz47AOu', 'jtrevena16@tiny.cc', 'admin', '703 499 6353', 'Jilli', 'Trevena');
insert into Users (login, password, email, role, phone, name, surname) values ('wsnap17', 'mVMznCbiikOw', 'wsnap17@dedecms.com', 'user', '411 174 5761', 'Wilek', 'Snap');
insert into Users (login, password, email, role, phone, name, surname) values ('rleyburn18', 'jYD1hPe', 'rleyburn18@rambler.ru', 'admin', '954 134 1830', 'Rasia', 'Leyburn');
insert into Users (login, password, email, role, phone, name, surname) values ('aeastby19', 'oObqkj', 'aeastby19@google.com.br', 'admin', '781 507 7251', 'Almeta', 'Eastby');
insert into Users (login, password, email, role, phone, name, surname) values ('pgwinnell1a', 'c3nE2mC', 'pgwinnell1a@tinypic.com', 'user', '801 259 7670', 'Pierson', 'Gwinnell');
insert into Users (login, password, email, role, phone, name, surname) values ('gbirth1b', 'snsTSw62jM4n', 'gbirth1b@xing.com', 'user', '932 886 4848', 'Gaylene', 'Birth');
insert into Users (login, password, email, role, phone, name, surname) values ('jdoornbos1c', '2mvyrHA2', 'jdoornbos1c@sbwire.com', 'admin', '947 633 2461', 'Joanne', 'Doornbos');
insert into Users (login, password, email, role, phone, name, surname) values ('dascroft1d', '2dhnYKXz', 'dascroft1d@slideshare.net', 'admin', '946 819 6842', 'Danella', 'Ascroft');
